import os
import json

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from google import genai

from app.database import get_db
from app.models import SocialPost, Campaign
from app.schemas.social_post import (
    SocialPostCreate,
    SocialPostResponse,
)


router = APIRouter(
    prefix="/social-posts",
    tags=["Social Posts"],
)


# ---------------------------------------------------------
# DAY THEMES
# ---------------------------------------------------------

DAY_THEMES = {
    1: "Awareness",
    2: "Benefits",
    3: "Problem → Solution",
    4: "Offer / Urgency",
    5: "Final Reminder / CTA",
}


# ---------------------------------------------------------
# GENERATE AI POST
# ---------------------------------------------------------

def _generate_post_with_gemini(
    campaign: Campaign,
    day_number: int,
    platform: str,
) -> str:

    api_key = os.environ.get("GEMINI_API_KEY")

    if not api_key:
        raise RuntimeError(
            "GEMINI_API_KEY not set"
        )

    client = genai.Client(
        api_key=api_key
    )

    theme = DAY_THEMES.get(
        day_number,
        "Engagement",
    )

    prompt = f"""
You are an expert social media marketing copywriter.

Create ONE unique social media post for the campaign below.

CAMPAIGN INFORMATION:
- Campaign name: {campaign.campaign_name}
- Objective: {campaign.objective}
- Goal: {campaign.goal}
- Product / Service: {campaign.product_label}
- Target audience: {campaign.target_segment}
- Tone: {campaign.tone}
- Additional information: {campaign.additional_info or "None"}

POST INFORMATION:
- Day: {day_number}
- Content theme: {theme}
- Platform: {platform}

IMPORTANT REQUIREMENTS:

1. Create a completely different post for this specific day.
2. Do not copy the campaign's existing generated content word-for-word.
3. The post must be appropriate for {platform}.
4. The post must match the "{theme}" theme.
5. Keep the tone consistent with "{campaign.tone}".
6. Mention the product naturally.
7. Include a clear marketing message.
8. Include a suitable call-to-action.
9. Do not mention that the content was generated by AI.
10. Do not include explanations outside the post.
11. Return ONLY valid JSON.

Return exactly:

{{
    "content": "the complete social media post"
}}
"""

    response = client.models.generate_content(
        model="gemini-flash-latest",
        contents=prompt,
        config={
            "response_mime_type": "application/json"
        },
    )

    result = json.loads(response.text)

    content = result.get("content")

    if not content:
        raise RuntimeError(
            "Gemini returned empty post content."
        )

    return content


# ---------------------------------------------------------
# CREATE / GENERATE SOCIAL POST
# ---------------------------------------------------------

@router.post(
    "/",
    response_model=SocialPostResponse,
)
def create_social_post(
    data: SocialPostCreate,
    db: Session = Depends(get_db),
):

    # -----------------------------------------------------
    # 1. Find campaign
    # -----------------------------------------------------

    campaign = (
        db.query(Campaign)
        .filter(
            Campaign.campaign_id
            == data.campaign_id
        )
        .first()
    )

    if not campaign:
        raise HTTPException(
            status_code=404,
            detail="Campaign not found",
        )

    # -----------------------------------------------------
    # 2. Validate day
    # -----------------------------------------------------

    if data.day_number < 1:
        raise HTTPException(
            status_code=400,
            detail="Day number must be at least 1.",
        )

    # -----------------------------------------------------
    # 3. Validate platform
    # -----------------------------------------------------

    channels = campaign.channels or []

    if data.platform not in channels:
        raise HTTPException(
            status_code=400,
            detail=(
                f"Platform '{data.platform}' "
                "is not selected for this campaign."
            ),
        )

    # -----------------------------------------------------
    # 4. Generate post using Gemini
    # -----------------------------------------------------

    try:

        content = _generate_post_with_gemini(
            campaign=campaign,
            day_number=data.day_number,
            platform=data.platform,
        )

    except Exception as e:

        print(
            f"Social post generation failed: {e}"
        )

        raise HTTPException(
            status_code=500,
            detail=(
                "Failed to generate social media post."
            ),
        )

    # -----------------------------------------------------
    # 5. Save generated post
    # -----------------------------------------------------

    post = SocialPost(
        campaign_id=data.campaign_id,
        day_number=data.day_number,
        platform=data.platform,
        content=content,
        status="Generated",
    )

    db.add(post)
    db.commit()
    db.refresh(post)

    return post